# Generated by Django 5.2.4 on 2025-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("confirmed", "Подтверждена"),
                    ("cancelled", "Отменена"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус записи",
            ),
        ),
    ]
