# Generated by Django 5.2.4 on 2025-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic_website", "0003_service_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=200)),
                ("note_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
